### ISSUE TITLE
Virtual Size

### ISSUE THREAD

**Issue by brunnels** [parabuzzle/craneoperator#19]
Quick question.  I just noticed when looking at the image for craneoperator that it's virtual size is 1.4GB.  Why is it so large?

**Comment by parabuzzle** [comment]
So I looked into this and its because it builds off of my ruby image: 

https://hub.docker.com/r/parabuzzle/ruby (https://github.com/parabuzzle/docker-ruby)

That image installs a bunch of boilerplate that I use in almost all of my ruby projects (its kind of a catch all container for my projects). It installs these pacakages:

```
nodejs
build-essential
chrpath libssl-dev
libxft-dev libfreetype6
libfreetype6-dev
libfontconfig
libfontconfig1-dev
phantomjs-2.1.1
```

These packages aren't actually used in this specific project and I may be able to look at skipping my deve container and using the base ruby container (https://hub.docker.com/r/_/ruby/) or even the slim ruby container. 

That's where all the bloat is coming from.

to be honest, I really didn't see it as much of problem or even noticed until you just mentioned it.

**Comment by brunnels** [comment]
Okay, thanks for the explanation.  Smaller would be good but not a big deal.

**Comment by parabuzzle** [comment]
reduced it down to 990.2 MB just by cutting out my intermediate dev container. Version 2.1.3 is built with the reduced bloat :)
